### ISSUE TITLE
如果当时网络有问题呢？

### ISSUE THREAD

**Issue by 183883324** [iDeMonnnnnn/CrashHandler#2]
![ylhg0w3t xfr4v 7g begbc](https://user-images.githubusercontent.com/37425595/47488107-49c22180-d876-11e8-85f8-c950491720ca.png)
这个流程有没问题？  崩溃的时候能上传服务器嘛？

**Comment by DeMonLiu623** [comment]
下面第2条的方法只是提供一个获取全部日志文件路径的方法，需要自己根据获取的路径写方法去上传，然后自己去删除，没有做自动上传的功能。（可能我是没说清楚）
1. 为方便查看，收集的信息存储到txt文件中，然后默认保存在sd卡根目录/你的app_name/Crash/ (如：storage/emulated/0/ErrorCatch/Crash/2018-09-21 09:42:59.txt)
2. CrashHandler.getCrashReportFiles(Context ctx)方法可以返回所有的错误信息文件路径，可以根据文件路径上传到服务器，然后将其删除，防止重复上传。

**Comment by 183883324** [comment]
好吧， 你就相当于只是做了一个收集存在text文件    还是很感谢  。剩下的就自己写咯。
